### ISSUE TITLE
Layout module doesn't handle multiple layouts properly

### ISSUE THREAD

**Issue by mahmoudhossam** [tobi-wan-kenobi/bumblebee-status#177]
I'm currently using bumblebee with the following Xorg configuration:

```
Section "InputClass"
        Identifier "system-keyboard"
        MatchIsKeyboard "on"
        Option "XkbLayout" "us,ara"
        Option "XkbVariant" ",qwerty_digits"
        Option "XkbOptions" "caps:swapescape"
EndSection
```

The layout module shows as follows:

![Imgur](https://i.imgur.com/HE4bINY.png)

It should detect and display the active layout(s) and allow switching between them as is the case in gnome-panel, for example.

**Comment by tobi-wan-kenobi** [comment]
Yeah, seems the `layout` module doesn't work as expected when you have multiple keyboard layouts configured.

Will look into that, might take some time, though, as I'm not really familiar with the output of `setxkbmap` and might have to rewrite large parts of the module....

Stay tuned & sorry for the inconvenience!

**Comment by tobi-wan-kenobi** [comment]
Please let me know whether this fixes your issue. I have do admit I'm only like 30% convinced I got the usage of `setxkbmap` correctly. Especially the "variant" stuff threw me off a bit :)

**Comment by tobi-wan-kenobi** [comment]
@mahmoudhossam Hmm... actually, the widget should update it's output once per second (unless you've configured a different update interval).

Right now, I assume that whatever language is first in the output of `setkxbmap -query` is the active one, maybe that's wrong? Could you check, maybe?

Thanks!

**Comment by mahmoudhossam** [comment]
@tobi-wan-kenobi This is what currently happens when I switch layouts:

![layout switch](https://i.imgur.com/n24kDND.png)

Note how the module now removes the variants I've set in Xorg.conf.

**Comment by tobi-wan-kenobi** [comment]
Sorry about those issues :-(

I actually had the variants in the code, must be some kind of  bug.

Will investigate further...

**Comment by tobi-wan-kenobi** [comment]
I can't reproduce this, could you maybe describe the error in a bit more detail?

My test setup:
1. Have 3 layouts:
```
$ setxkbmap -query
rules:      evdev
model:      pc105
layout:     at,us,us
variant:    ,,dvorak
```
2. statusbar shows "at" as active layout
3. left-click layout widget, switches to "us":
```
$ setxkbmap -query
rules:      evdev
model:      pc105
layout:     us,us,at
variant:    ,dvorak,
```
4. left-click layout widget again, switches to "us:dvorak":
```
$ setxkbmap -query
rules:      evdev
model:      pc105
layout:     us,at,us
variant:    dvorak,,
```

I tried the same with adding "ara" as layout and "querty_digits" as variant, and it worked fine, too (except for the fact that my terminal cannot render arabic characters...)

Are you clicking on the widget and the variants get lost, or does that happen as soon as the bar starts?

**Comment by mahmoudhossam** [comment]
@tobi-wan-kenobi I think I know why this happens.

When I press the keyboard combination for layout change, no changes happen to the order of the layouts when queried with `setxkbmap -query`, that's why the widget still displays "us" as the current layout.

PS: I'm using the version from Archlinux's AUR (patched the layout module manually), should I try running the master branch instead?

**Comment by tobi-wan-kenobi** [comment]
@mahmoudhossam Ah, that explains a lot.

No, `master` wouldn't change anything, the changes are in the `layout` module exclusively. I'll investigate whether there's a better way to get the currently selected keyboard.

Could you, if you have time, maybe paste the output for `setxkbmap -v -print`, in both situations?

Thanks a lot!

**Comment by mahmoudhossam** [comment]
@tobi-wan-kenobi Both layouts print exactly the same output:

```
Trying to build keymap using the following components:
keycodes:   evdev+aliases(qwerty)
types:      complete
compat:     complete
symbols:    pc+us+ara:2+inet(evdev)+group(win_space_toggle)+capslock(swapescape)
geometry:   pc(pc105)
xkb_keymap {
        xkb_keycodes  { include "evdev+aliases(qwerty)" };
        xkb_types     { include "complete"      };
        xkb_compat    { include "complete"      };
        xkb_symbols   { include "pc+us+ara:2+inet(evdev)+group(win_space_toggle)+capslock(swapescape)"  };
        xkb_geometry  { include "pc(pc105)"     };
};
```

I don't think there's a way to do this using `setxkbmap`.

I was able to get the current layout by using something like [this](https://github.com/Kuraisu/python-xkeyboard) though, but it only works on Python 2.x.

**Comment by mahmoudhossam** [comment]
Both print the exact same output:
``` 
$ localectl status
   System Locale: LANG=en_US.UTF-8
       VC Keymap: us
      X11 Layout: us,ara
     X11 Variant: ,qwerty_digits
     X11 Options: caps:swapescape
```

I know it's really weird, but it seems that there's no way to get the current layout from the CLI.

That's why modules like the one I showed you exist.

**Comment by tobi-wan-kenobi** [comment]
:-/ I'd rather avoid using a python module that is not widely available, to be honest. I will try to have a look whether I can rig something together with the Python C bindings, but this is seriously going to take some time. I'm very sorry for that....

**Comment by tobi-wan-kenobi** [comment]
Update: I'm not neglecting this issue, I can now call the libX11 library from Python and just need to find the time to figure out how to query the layouts.

**Comment by mahmoudhossam** [comment]
@tobi-wan-kenobi I really appreciate taking all this time to solve this, let me know if I there's anything you'd like me to test.

You can also look at python-xkeyboard for inspiration.

**Comment by tobi-wan-kenobi** [comment]
Hi,

I think there's a partial success: I'm now using `xkbgroup` (https://pypi.python.org/pypi/xkbgroup) and am able to successfully (I hope...) display the current layout.

I am not yet able to correctly set the layout, however. Maybe I can just use `setxkeymap` for that.

In order to not mess with existing code, I've added this functionality as a separate, experimental module called `layout-xkb`.

**Comment by tobi-wan-kenobi** [comment]
I've now implemented layout switching similar to how it's done in the `layout` module by invoking `set-xkbmap`.

Please let me know whether that makes the module work as intended for you.

Thanks for your patience :)

**Comment by mahmoudhossam** [comment]
@tobi-wan-kenobi Running `bumblebee-status -t gruvbox-powerline -m cpu memory layout datetime amixer -p datetime.format="%T %e/%m/%Y" nic.exclude="lo,virbr,docker,vboxnet,veth,br"` now returns an error:

```
Traceback (most recent call last):
  File "/usr/sbin/bumblebee-status", line 73, in <module>
    main()
  File "/usr/sbin/bumblebee-status", line 45, in main
    inp=inp,
  File "/usr/share/bumblebee-status/bumblebee/engine.py", line 117, in __init__
    self._aliases = self._read_aliases()
  File "/usr/share/bumblebee-status/bumblebee/engine.py", line 155, in _read_aliases
    mod = importlib.import_module("bumblebee.modules.{}".format(module["name"]))
  File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 978, in _gcd_import
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load
  File "<frozen importlib._bootstrap>", line 950, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 205, in _call_with_frames_removed
  File "/usr/share/bumblebee-status/bumblebee/modules/layout-xkb.py", line 16, in <module>
    from thirdparty.xkbgroup import *
  File "/usr/share/bumblebee-status/thirdparty/xkbgroup/__init__.py", line 14, in <module>
    from .core import XKeyboard, X11Error
  File "/usr/share/bumblebee-status/thirdparty/xkbgroup/core.py", line 31, in <module>
    from .xkb import *
  File "/usr/share/bumblebee-status/thirdparty/xkbgroup/xkb.py", line 7652, in <module>
    cfree = _libraries['libX11.so.6'].cfree
  File "/usr/lib/python3.6/ctypes/__init__.py", line 361, in __getattr__
    func = self.__getitem__(name)
  File "/usr/lib/python3.6/ctypes/__init__.py", line 366, in __getitem__
    func = self._FuncPtr((name_or_ordinal, self))
AttributeError: /usr/lib/libX11.so.6: undefined symbol: cfree
```

Can you update the AUR package for me to test with? I'm using [this package](https://aur.archlinux.org/packages/bumblebee-status-git).

**Comment by tobi-wan-kenobi** [comment]
Hi,

1. sorry about that! I misunderstood how `xkbgroup` works and thought the modules built on my system should be generally working. I've now removed the 3rdparty `xkbgroup`, please try to run `pip3 install xkbgroup` and try the module again.

2. Unfortunately, this means that, right now, `layout-xkb` requires Python3, I have opened a PR for Python2.7 compatibility, however (https://github.com/hcpl/xkbgroup/pull/8)

3. @glaxx is the maintainer of the `bumblebee-status-git` module, but I believe with the removed 3rdparty modules, it should update (semi?) automatically.

Hope this helps!

**Comment by mahmoudhossam** [comment]
@tobi-wan-kenobi Still doesn't work, but it's xkbgorup's fault.

It seems I'm affected by this hcpl/xkbgroup#7

I'm using Arch Linux which uses a newer version of libc which is causing this problem.

**Comment by mahmoudhossam** [comment]
@tobi-wan-kenobi Just installed xkgroup's master branch, now layout-xkb works perfectly!

Might wanna decrease the timeout a bit though.

I think the solution to this problem is to include xkbgroup's master as a dependency of bumblebee?

**Comment by tobi-wan-kenobi** [comment]
Glad to hear it (finally) works!

Yeah, that would be the short-term solution. Mid-term, I hope that there will be a xkbgroup release on PIP that 1. supports Python 2.7 and 2. works with missing cfree().

Thanks & have a nice day!

**Comment by hcpl** [comment]
@mahmoudhossam @tobi-wan-kenobi `xkbgroup` 0.2.0 released, please check it out!

**Comment by mahmoudhossam** [comment]
@hcpl Thank you!

@tobi-wan-kenobi Now I think we can safely include xkbgroup as a dependency for bumblebee.

**Comment by tobi-wan-kenobi** [comment]
@mahmoudhossam I fully agree, the current implementation seems a safe choice now.

**Comment by RobinVogel** [comment]
I just spent some time playing around with this issue.
What happened in my setup is that by using this line
`exec --no-startup-id setxkbmap -layout "fr,us,ru"  -option "grp:alt_shift_toggle"`
in my `.config/i3/config`, when I switch the layout, the keymap changes but the `setxkbmap -query` still gives out the layout `fr,us,ru`.

I solved this locally by creating a script that changes the layout (`fr,us,ru` then `us,ru,fr`, etc...) instead of using the option `grp:alt_shift_toggle` above. And I use:
```
    exec --no-startup-id setxkbmap -layout "fr,us,ru"
    bindsym $mod2+space exec "~/Documents/i3/change_layout.sh"
```
where change layout is:
```
#!/bin/bash
arr_layouts=$(setxkbmap -query | grep "^layout:" | sed "s/layout:\s *\([a-z,]*\)/\1/g")
IFS="," read -a arr_layouts <<< $arr_layouts
n_layouts=${#arr_layouts[@]}
new_layout=$(for ((i=1; i<=$n_layouts-1; i++)); do printf ${arr_layouts[$i]}","; done)${arr_layouts
    [0]}
setxkbmap $new_layout
```

I'm sorry I don't have a more thorough insight on this.

**Comment by tobi-wan-kenobi** [comment]
Excellent question... I have no idea. Have you given the module `layout-xkb` a go? Maybe it's more stable (it uses a library instead of a CLI tool).
Other than that, I completely failed to find a way to reliably retrieve the current keyboard layout. There *has* to be a way, since a lot of desktop environments offer that, but I didn't find any information on it.

**Comment by RobinVogel** [comment]
Yes I'm sorry, I tried that, but it gave me this result:
![2019-01-30t20 15 12 01 00](https://user-images.githubusercontent.com/7306538/52006187-dad71300-24cb-11e9-95c0-04b1c0b9f893.png)

**Comment by tobi-wan-kenobi** [comment]
For `layout-xkb`, you need the python module `xkb`, which, as far as I know, is only available via pip right now. Is that missing, maybe?

**Comment by RobinVogel** [comment]
![2019-01-31t20 30 33 01 00](https://user-images.githubusercontent.com/7306538/52080046-302c2680-2597-11e9-9d5f-dff56abc192d.png)

The calls to python2 and python3 were to check I was using the python of my system and not my anaconda python. All of those have xkbgroup now. I have the same result.
