### ISSUE TITLE
Probleme datetime module

### ISSUE THREAD

**Issue by amanAnkh** [tobi-wan-kenobi/bumblebee-status#269]
|    Q        |   A
|------------ | -----
| Version     | x
| i3wm        | 4.15.0.1
| bumblebee   | https://aur.archlinux.org/packages/bumblebee-status/
| task   | 2.5.1.1

#### Support Question

Hello, I use bumblebee-status, I encounter a problem with a module of the one if.
if i use datetime (time/date/datetime) my bar display error (1).

If i run in my termninal bumblebee-status with my bar setting, I have an import error from taskwarrior that I still installed via pip. If anyone has a lead, I thank you in advance. If any information is missing I'm listening.

[ STATUS COMMAND ]
`status_command bumblebee-status -m cpu disk:root memory datetime time.format="%H:%M CW %V" date.format="%A, %d %b %Y" -t solarized-powerline`

[ ERROR ]
`Error: status_command process exited unexpectedly (exit 1)`

[ TRY TO TERMINAL]
```
purple% bumblebee-status -m cpu disk:root memory datetime mpd -p root.path=/ time.format="%H:%M CW %V" date.format="%A, %d %b %Y" -t solarized-powerline


failed to import taskwarrior: argument of type 'FileNotFoundError' is not iterable
Traceback (most recent call last):
  File "/usr/bin/bumblebee-status", line 74, in <module>
    main()
  File "/usr/bin/bumblebee-status", line 46, in main
    inp=inp,
  File "/usr/share/bumblebee-status/bumblebee/engine.py", line 143, in __init__
    self.load_modules(config.modules())
  File "/usr/share/bumblebee-status/bumblebee/engine.py", line 198, in load_modules
    mod = self._load_module(module["module"], module["name"])
  File "/usr/share/bumblebee-status/bumblebee/engine.py", line 240, in _load_module
    "config": self._config
  File "/usr/share/bumblebee-status/bumblebee/modules/datetime.py", line 37, in __init__
    lcl = self.parameter("locale", ".".join(l))
TypeError: sequence item 0: expected str instance, NoneType found```

**Comment by fredj** [comment]
Hi, maybe this issue is already fixed with #265

**Comment by amanAnkh** [comment]
Thank you for this answer which makes me advance in the quest of time !
new fix new problem, now it's the time module that's not finding. Maybe you have some idea.

```
purple% bumblebee-status -m cpu sensors memory dnf datetime weather time.format="%H:%M CW %V" date.format="%A, %d %b %Y"
/usr/lib/python3.6/site-packages/requests/__init__.py:80: RequestsDependencyWarning: urllib3 (1.23) or chardet (3.0.4) doesn't match a supported version!
  RequestsDependencyWarning)
Traceback (most recent call last):
  File "/usr/share/bumblebee-status/bumblebee/engine.py", line 235, in _load_module
    module = importlib.import_module("bumblebee.modules.{}".format(module_name))
  File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 941, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'bumblebee.modules.time'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/bumblebee-status", line 74, in <module>
    main()
  File "/usr/bin/bumblebee-status", line 46, in main
    inp=inp,
  File "/usr/share/bumblebee-status/bumblebee/engine.py", line 143, in __init__
    self.load_modules(config.modules())
  File "/usr/share/bumblebee-status/bumblebee/engine.py", line 198, in load_modules
    mod = self._load_module(module["module"], module["name"])
  File "/usr/share/bumblebee-status/bumblebee/engine.py", line 237, in _load_module
    raise bumblebee.error.ModuleLoadError(error)
bumblebee.error.ModuleLoadError: No module named 'bumblebee.modules.time'

**Comment by ReiLucio** [comment]
First -Syu [python-requests bug](https://git.archlinux.org/svntogit/packages.git/commit/trunk?h=packages/python-requests&id=cd793259b3595b148a05f7c238aaf97327503454), bumblebee-status -l modules. btw you forgot "-p" before the parameters.

**Comment by ReiLucio** [comment]
Alto try `datetime.format=`  instead of  `time.format=` + `date.format=` , my conf.

`status_command bumblebee-status -m ping traffic disk memory cpu datetime uptime pasink -p ping.adress=8.8.8.8 datetime.format="%a %d %b %R" traffic.exclude="vmnet1,vmnet8,lo,enp3s0" -t greyish-powerline`

**Comment by tobi-wan-kenobi** [comment]
Also, to narrow down the issue, could you please paste the output of:

bumblebee-status -m datetime
bumblebee-status -m time

ie. without parameters and other modules?

many thanks!

**Comment by amanAnkh** [comment]
After use `-p` it works fine !
Thank you for all your messages, i close the issue
