### ISSUE TITLE
No limit on pulseaudio scrolling

### ISSUE THREAD

**Issue by Morganamilo** [tobi-wan-kenobi/bumblebee-status#354]
#### Summary
Affected module: pasink

There is no limit when adjusting the volume when scrolling over the pasink module.

Especially on momentum enabled trackpads where one flick of the fingers can send the volume flying to over 1000%.

#### How to reproduce
Scroll until the volume is >100%

#### Expected behavior
Volume should be limited to 0-100%

**Comment by tobi-wan-kenobi** [comment]
Thanks for the report, this is a good idea!

I have implemented a solution in 3d9e170, please let me know whether it works for you. 

You can now set the parameter "limit" (.e.g. `-p pasink.limit=100%`), and bumblebee-status will not set the volume to anything higher than that. Note that you can still achieve a higher volume by using other tools, such as pavucontrol.

**Comment by Morganamilo** [comment]
That's 1/2 down already. Seem's to work perfect. I would suggest this also be the default, but a flag ain't that inconvenient.

**Comment by tobi-wan-kenobi** [comment]
:+1: I was thinking about the default, but I am always a bit reluctant to change the default behaviour once the module is out.

**Comment by Morganamilo** [comment]
Actually there seem to be 2 more little bugs with this. The bar adds 2 to the volume per scroll. If the volume is at 99% then it will go to 101% instead of maxing out on 100%.

Also it appears I can still get to 101% and 102% by just scrolling really really fast. Race condition maybe?

**Comment by tobi-wan-kenobi** [comment]
Thanks for the report, I think I see where this is coming from. Me being lazy :)

I'll have look and fix it.
